---
- hosts: all
  gather_facts: no
  become: false
  tasks:

   - name: Run remote PowerShell Script
     win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Users\Administrator\example-update.ps1 #Example of a execution of a Powershell script on the destination server.