---
- hosts: all
  gather_facts: no
  become: false
  tasks:

   - name: Run remote PowerShell Script
     win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Users\Administrator\install\installRIM.ps1